### ISSUE TITLE
Application freezes on Downloads tab

### ISSUE THREAD

**Issue by ZackaryH8** [XboxVillain/XBLMarketplace-For-PC#2]
# Explanation
The application crashes when changing to the download tab after initiating a direct download.

# Reproduction Steps

- Start any download using Direct Download
- Change to the download tab
- The application will crash

**Comment by oSerenity** [comment]
> # Explanation
> The application crashes when changing to the download tab after initiating a direct download.
> 
> # Reproduction Steps
> * Start any download using Direct Download
> * Change to the download tab
> * The application will crash

don't use the application downloader as is not perfect and needs revision
